# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0.0)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_specs', to='specifications.Setup')),
            ],
        ),
    ]
